import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextThemeProvider from "./themeProvider";
import { AuthProvider } from "@/components/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next auth session",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
